
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liujx0804/springcloud-leaning/    # 配置git仓库的地址
          search-paths: conf                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 2876564629@qq.com                                             # git仓库的账号
          password: 7k8;_&fAHA6HT0                                             # git仓库的密码
